### ISSUE TITLE
Doesn't work with secure cookies enabled

### ISSUE THREAD

**Issue by GitsMcGee** [t2v/play2-auth#104]
Hi @gakuzzzz. I'm not sure if this is a bug, or if I am just doing something wrong. I found that authentication worked great with I ran my app with `activator run`, but would fail when I ran my app with `activator start`. After a bit of debugging, I found the culprit to be 
```scala
  /**
   * Whether use the secure option or not use it in the cookie.
   * However default is false, I strongly recommend using true in a production.
   */
  override lazy val cookieSecureOption: Boolean = play.api.Play.isProd(play.api.Play.current)
```

If I change it to always be `false`, then both `run` and `start` work fine. When secure cookies are enabled, my app never redirects to the appropriate page after I login. It just keeps asking me to login. 

Any ideas?

**Comment by psuter** [comment]
Hello, I'm observing the same behavior as @GitsMcGee with my test apps.

Best regards,
PS

**Comment by psuter** [comment]
@GitsMcGee I ran into the same issue. After reading on secure cookies, I realized this cannot work unless you are running your application behind SSL (https). After creating a self-signed certificate and configuring nginx to accept SSL and act as a proxy for my Play app, the library works as intended.

Thanks @gakuzzzz for a great library!

**Comment by gakuzzzz** [comment]
Oh! I see.

very thanks! @psuter
I misunderstood this problem.

@GitsMcGee 
`play start` command launch the application at `Prod` mode.
so, cookieSecureOption returns true and it needs SSL.

**Comment by GitsMcGee** [comment]
Ahh. That makes sense. Thanks @psuter and @gakuzzzz for the help!
