### ISSUE TITLE
could not find implicit value for parameter req: jp.t2v.lab.play2.stackc.RequestWithAttributes[_]

### ISSUE THREAD

**Issue by satybald** [t2v/play2-auth#110]
I'm trying to to get the current user profile. I've setup a nested Actions for my API.

```
trait ErrorHandlingSecured extends Controller with AuthElement with AuthConfigImpl  {
  def APISecuredNormalUser(f: Request[AnyContent] => SimpleResult): Action[AnyContent] =
    StackAction(AuthorityKey -> NormalUser) { implicit request =>
      try { f(request) }
      catch {
        case msg: Throwable => {
          InternalServerError(Json.toJson(Json.obj("code" -> "500", "message" -> msg.toString)))
        }
      }
    }
}
```

and then I'm calling loggedIn in my controller

```
object OrdersSiteApi extends Controller with ErrorHandlingSecured{
  def all() = APISecuredNormalUser { implicit request =>
   val user = loggedIn
   ...
  }
}
```

I get the following errror:

could not find implicit value for parameter req: jp.t2v.lab.play2.stackc.RequestWithAttributes[_]

Could you please advice how would be possible to get the current user from the controller?

**Comment by vooolll** [comment]
@gakuzzzz It would be great to have information about body parser at documentation, it is very helpful, thank you.
