### ISSUE TITLE
Method authorization

### ISSUE THREAD

**Issue by viejodecaldas** [t2v/play2-auth#113]
Hi, 

I want to know if there is a way to do some method authorization via annotations, like you do in Java, checking the role or the user group.

Thanks in advance!

**Comment by gakuzzzz** [comment]
Hi,

You can write annotation macro like follows.

```scala
@authority(Admin)
def index = Action {
  ...
}
```

convert to

```scala
def index = StackAction(AuthorityKey -> Admin) {
  ...
}
```

Best
