### ISSUE TITLE
Make authenticated user available in authorizationFailed

### ISSUE THREAD

**Issue by samco** [t2v/play2-auth#115]
When authenticaton is successful (credentials are correct) but authorization fails (e.g. user permissions are insufficient), the authorizationFailed method is called. The logged in user is not made available.

A good user experience would be for authorizationFailed to display a page with look and feel consistent with the rest of the application and with information useful to the user instead of the short messages in the examples. This would be made much easier if the logged in user were available to authorizationFailed.

**Comment by gakuzzzz** [comment]
I agree. `authorizationFailed` should be acceptable `User` object.

I will fix it.

**Comment by gakuzzzz** [comment]
I have published 0.13.1-SNAPSHOT to Sonatype.

Would you check it? @samco

**Comment by samco** [comment]
This looks good to me. Thanks very much.

**Comment by gakuzzzz** [comment]
Thanks, I'll publish stable 0.13.1 at some early date
