### ISSUE TITLE
access to Action with multiple UserPermission

### ISSUE THREAD

**Issue by roohi66** [t2v/play2-auth#126]
hey 
I use this module and it's very cool
I have a problem i wanna 2 or 3 User can access to an action like :
  def sample = StackAction(AuthorityKey -> AdminPermission,AuthorityKey -> ModeratorPermission) { implicit request =>
..
.
now if i try with  2 permission no one can access to Action. is there any way to limit action with multiple role ?

Thanks

**Comment by gakuzzzz** [comment]
Yes, you can define authority to any type.

for example

```scala
trait AuthConfigImpl extends AuthConfig {
  type Authority = Set[Permission]
  ...
}

object MyController extends ... {

  def sample = StackAction(AuthorityKey -> Set(AdminPermission, ModeratorPermission)) { implicit request =>
  }

}
```

or

```scala
sealed abstract class PermissionGroup(permissions: Permission*)
object PermissionGroup {
  object All extends PermissionGroup(AdminPermission, ModeratorPermission)
  ...
}

trait AuthConfigImpl extends AuthConfig {
  type Authority = PermissionGroup
  ...
}

object MyController extends ... {

  def sample = StackAction(AuthorityKey -> PermissionGroup.all) { implicit request =>
  }

}
```

**Comment by roohi66** [comment]
Thank you
I have an error in sample one : 

pattern type is incompatible with expected type;
 found   : models.StudentPermission.type
 required: AuthConfigImpl.this.Authority
    (which expands to)  scala.collection.immutable.Set[models.UserPermission]

def authorize(user: User, authority: Authority)(implicit ctx: ExecutionContext): Future[Boolean] = Future.successful {
86    (user.permission, authority) match {
87      case (AdministratorPermission, _) => true
88      case (StudentPermission, StudentPermission) => true 
89      case (SchoolPermission, SchoolPermission) => true
90      case (FinancePermission, FinancePermission) => true
91      case (TeacherPermission, TeacherPermission) => true
92
93      case (StudentAffPermission, StudentAffPermission) => true

**Comment by gakuzzzz** [comment]
You need to override the `authorize` method as the type matches `Authority`.

The `authorize` method has a specific logic in your application.

**Comment by roohi66** [comment]
Same problem again
please check it out the code https://github.com/mitrus/School/blob/7182ce8d99860aeb83607c3953c5c03c3ef3b6fd/app/controllers/AuthConfigImpl.scala#L90

I need your help :(

**Comment by gakuzzzz** [comment]
mmm, I might not catch your problem...
What is occurred?

**Comment by roohi66** [comment]
Error :
![screen shot 1394-02-19 at 7 49 15 am](https://cloud.githubusercontent.com/assets/9565737/7548483/0244b76e-f620-11e4-80bf-275b4ce2509e.png)

this is my original code :
https://github.com/mitrus/School/blob/7182ce8d99860aeb83607c3953c5c03c3ef3b6fd/app/controllers/AuthConfigImpl.scala#L90

**Comment by roohi66** [comment]
any offer ?
could you please upload a sample project ?

**Comment by gakuzzzz** [comment]
You must match types in `authorize` method.
If you define `Authority` as `Set[Role]`, the `authority` value is an instance of `Set[Role]`.
However your pattern is `Role`. It is type miss match.

In Japanese, there is a sample http://tsukaby.com/tech_blog/archives/804

**Comment by gakuzzzz** [comment]
Does solve it?

I close this, if there are some problems, use gitter https://gitter.im/t2v/play2-auth
thanks
