### ISSUE TITLE
play 2.4 builds.

### ISSUE THREAD

**Issue by indykish** [t2v/play2-auth#128]
Hi i tested out play 2.4 RC3 with our code
https://github.com/megamsys/megam_gateway.git

As play-auth depends on 2.3, my `cache` in play 2.4 gets evicted, hence my app fails to run saying "NoClass def found for CachePlugin"

Can you make a snapshot for 2.4 ?

**Comment by gakuzzzz** [comment]
Alright, I'll publish SNAPSHOT for 2.4-RC

**Comment by indykish** [comment]
@gakuzzzz Play 2.4 was released today. Can you make a snapshot or 0.13.3 ?

**Comment by gakuzzzz** [comment]
I published 0.14.0-SNAPSHOT that contains #133 

However it fails tests.
Would you help me?

**Comment by indykish** [comment]
Yes. 

A quick note play 2.4 only works with JDK 1.8

I  see a `Cache problem` in the travis ci.  The api was changed in 2.4.

**Comment by gakuzzzz** [comment]
Thanks, I removed oraclejdk7 from travis settings.

**Comment by indykish** [comment]
Ok. I will fork and check it out later in the day (after 6 hrs) :+1:   Good work @gakuzzzz

**Comment by barcahead** [comment]
any update for play 2.4 support?

**Comment by gakuzzzz** [comment]
It is blocked by some Play2 issue
https://github.com/playframework/playframework/issues/4488
https://github.com/playframework/playframework/issues/4591

If you don't need to use CacheIdContainer, would you use 0.14.0-SNAPSHOT?

**Comment by barcahead** [comment]
@gakuzzzz how to include 0.14.0-SNAPSHOT in play2.4 project?

**Comment by gakuzzzz** [comment]
add Sonatype snapshot resolver and add dependency play2-auth 0.14.0-SNAPSHOT

```scala
resolvers += Resolver.sonatypeRepo("snapshots")
libraryDependencies += "jp.t2v" %% "play-auth" % "0.14.0-SNAPSHOT" 
```

**Comment by barcahead** [comment]
@gakuzzzz got it, thanks

**Comment by Enalmada** [comment]
FYI When I use 0.14.0-SNAPSHOT everything works fine in dev mode but in production (start) mode the login page just redirects back to login.  Changing back to 0.13.2 appears to work fine for me with play 2.4.   (I believe I am just following the basic usage from instructions and the stateless idContainer override)

**Comment by gakuzzzz** [comment]
Thanks for reporting.
the intended behavior. the `TokenAccessor` default implementation is changed to more secure.
https://github.com/t2v/play2-auth/pull/133/files#diff-6f968b3524e16933f29a65ff5ece7471R53
In production, use SSL or override cookieSecureOption to false explicitly.

**Comment by brianwawok** [comment]
So what is the status on this? We are waiting on a play 2.4.1 release, no more changes needed on the play2 auth side?

I tried a few weeks ago with 2.4.0 and hit all the problems described above.. have not tried again, because the play changes are kind of a pain.

**Comment by gakuzzzz** [comment]
sorry waiting for this.
It still has #133 test failure and It needs changing test helper API from #136.

If you have a nice idea that solves these, would you PR it?

**Comment by jmich41** [comment]
now we have a 2.4.1 and https://github.com/playframework/playframework/issues/4488 is fixed, will it work now?

**Comment by gakuzzzz** [comment]
0.14.0 has released
