### ISSUE TITLE
Cache dependency needed (Play 2.4)

### ISSUE THREAD

**Issue by misto** [t2v/play2-auth#134]
I'm migrating an application to Play 2.4 and I'm using your 0.14.0-SNAPSHOT. When running the application, I got a 
`RuntimeException: java.lang.NoClassDefFoundError: play/api/cache/Cache$` until I added the `cache` module to my app-dependencies. I'm not sure if that's just an issue of documentation or a bug, otherwise I would have created a pull-request.

**Comment by gakuzzzz** [comment]
Yes, It is an issue of documentation.
I changed the cache dependency to `provided`
https://github.com/t2v/play2-auth/pull/133/files#diff-215113124f1de02f228327ba7abb45f7R65
because apps what use before version conflicted old play library.

**Comment by gakuzzzz** [comment]
done ea86dfabd623898e5339cca57079f021aeafc4a8
