### ISSUE TITLE
Example with play-slick

### ISSUE THREAD

**Issue by djonmayer** [t2v/play2-auth#141]
Can you add please play2-auth-support to computer-database-sample of play-slick v1.0.0 (https://github.com/playframework/play-slick/tree/master/samples/computer-database)?

Regards
Djon

**Comment by gakuzzzz** [comment]
Only the information, I can't implement it.
What do for you do you how to authenticate, what authority the is needed where, unknown points too many...

**Comment by djonmayer** [comment]
Can you combine your basic-sample with it?

**Comment by gakuzzzz** [comment]
I still not understand what do you want...

Do I send PullRequest to https://github.com/playframework/play-slick/ ?

**Comment by gakuzzzz** [comment]
When you fork computer-database-sample and try to combine play2-auth, If you will have some question, We will answer these question.

best,

**Comment by djonmayer** [comment]
I've created a combination of both samples (https://github.com/djonmayer/play2-auth-slick)
But I get some errors during compilation. Can you check it out, please?

Regards

**Comment by gakuzzzz** [comment]
:+1: nice try!

when you write what compilation error has occurred, we can answer quickly :) 

It seems using Play2.4 and play2-auth 0.14.0
https://github.com/djonmayer/play2-auth-slick/blob/8132067f3d3404bb87f4642f40a55c99c1c320f1/project/plugins.sbt#L2
https://github.com/djonmayer/play2-auth-slick/blob/8132067f3d3404bb87f4642f40a55c99c1c320f1/build.sbt#L16

However [AuthCOnfigImpl](https://github.com/djonmayer/play2-auth-slick/blob/8132067f3d3404bb87f4642f40a55c99c1c320f1/app/controllers/AuthConfigImpl.scala) seems using old style for Play2.3 and play2-auth 0.13.0

Would you see currents README
https://github.com/t2v/play2-auth#usage

**Comment by djonmayer** [comment]
Thank you for your hint.
In your case has a function Account.findById() or Account.findByEmail() Option[Account] as return value. In my case it is Future[Option[Account]], so I get an error by mapping of loginForm / dataForm.

**Comment by gakuzzzz** [comment]
yes, you should change `dataForm` to handle `Future[Option[Account]]`

Play2 Form API document is here. https://www.playframework.com/documentation/2.4.2/ScalaForms

**Comment by marius-carp** [comment]
Hi @djonmayer,
I manged to fix some of those errors.
https://github.com/marius-carp/play2-auth-slick

**Comment by gakuzzzz** [comment]
thanks for your support comment, @marius-carp.

I close this issue. if there are some question, plese come gitter https://gitter.im/t2v/play2-auth :)
