### ISSUE TITLE
play 2.4.2 and can't decode cookie header

### ISSUE THREAD

**Issue by brianwawok** [t2v/play2-auth#142]
I see this message in my logs with play 2.4.2 and play2 auth 0.14.0 on every request

     [debug] play.api.mvc.Cookies - Couldn't decode the Cookie header containing:

This is coming from either

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/Http.scala#L898

or

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/Http.scala#L918

Everything seems to work..  not sure it matters?   

I have a pretty plane tokenAccessor defined:

      override lazy val tokenAccessor: TokenAccessor = new CookieTokenAccessor(
        cookieName =  "PLAY2AUTH_SESS_ID",
        cookieSecureOption = isProd(),
        cookieHttpOnlyOption = true,
        cookieDomainOption = {
          if(isProd()){
            Some("foobar.com")
          } else {
            None
          }
        },
        cookiePathOption =  "/",
        cookieMaxAge = Some(sessionTimeoutInSeconds)
      )

**Comment by gakuzzzz** [comment]
mmm, I can't reproduce...

Would you write small codes?

**Comment by brianwawok** [comment]
seems to be some localhost only crazyiness, can close this out
