### ISSUE TITLE
Q: sameAuthor doesn't even compile for me 

### ISSUE THREAD

**Issue by th-e** [t2v/play2-auth#145]
Currently I do not understand and even the compiler complains the type of the StackAction parameter `AuthorityKey -> sameAuthor(messageId)`
 of the edit method at
https://github.com/t2v/play2-auth/wiki/Advanced-usage%3A-----request-parameters

What am I doing wrong?

**Comment by gakuzzzz** [comment]
oh..., It's document is old.

Would you see https://github.com/t2v/play2-auth#changing-the-authorization-depending-on-the-request-parameters ?

I'll fix wiki

**Comment by gakuzzzz** [comment]
I had fixed wiki.
