### ISSUE TITLE
REST auth

### ISSUE THREAD

**Issue by plufz** [t2v/play2-auth#149]
Hi!

I'm looking at implementing authentication using this method https://github.com/jamesward/play-rest-security/ where you pass the token as a custom http header instead of using a cookie. Is it possible to pass the token over a custom header instead of a cookie in play2-auth?

Kind Regards!

**Comment by gakuzzzz** [comment]
Hi!

Yes, you can do it by using CustomTokenAccessor.

Would you see  HTTP Basic Authentication example https://github.com/t2v/play2-auth/tree/946af6164a8dd57b1b1d468cba3f77c259875138/sample/app/controllers/basic
or #112 ?

**Comment by plufz** [comment]
Looks great! Thanks a lot!
