### ISSUE TITLE
Question: Persistent remember me

### ISSUE THREAD

**Issue by maxmos10** [t2v/play2-auth#151]
I'm trying to do an implementation of remember me which last for one month.

I followed the example on https://github.com/t2v/play2-auth/tree/master/sample/app/controllers/rememberme. Then I override `AsyncIdContainer` to store the token in a database instead.

Where to go after this?

Should I change the behavior of [RememberMeTokenAccessor](https://github.com/t2v/play2-auth/blob/master/sample/app/controllers/rememberme/RememberMeTokenAccessor.scala) when checking for `remember` and `maxAge`? What's your thought?

**Comment by gakuzzzz** [comment]
I still not catch your problem...

Do you have what the trouble?

**Comment by maxmos10** [comment]
Hi gakuzzzz,

Following the example from `RememberMe`, I logged in using routes `/rememberme/`. 
After login is successful, I close the browser. Then, i believe that the Cookie `maxAge` will be set to None.

If I close the browser for the 3rd time, then user will have to login to access `/rememberme/messages/main`. How do I avoid that?

**Comment by gakuzzzz** [comment]
`maxAge == None` means that the cookie life is until the browser closing.
If you want to keep the session until browser reopen, you should write `maxAge` explicitly.

**Comment by maxmos10** [comment]
What should I check for `remember`? Since, the request session `rememberme` doesn't exist?
