### ISSUE TITLE
Same user multi connection

### ISSUE THREAD

**Issue by nesteban-aldera** [t2v/play2-auth#154]
Hi,

Currently, with default configuration, if a user log from computer A and, same user log from computer B, then Computer A session is no more available and require to signin again.

How to permit same user/account to login from differents computers ?

Thanks in advance

**Comment by shukla2009** [comment]
I think same is explained in 
https://github.com/t2v/play2-auth/issues/75

**Comment by nesteban-aldera** [comment]
You are right, thanks I follow the suggestion.

2015-08-28 15:03 GMT+02:00 Rahul Shukla <notifications@github.com>:
