### ISSUE TITLE
get logged in user in a filter

### ISSUE THREAD

**Issue by liorhar** [t2v/play2-auth#159]
what would be the way to access the logged in user when writing a http filter?
I mean the `AuthElement` trait assumes a controller in scope. is there a trait for filters?

**Comment by gakuzzzz** [comment]
The ActionBuilder of Play2(that play2-auth use internally) are resolved inside the Filter of Play2.
So it is so difficult that you access in play2 filter.

You can use stackable-controller or ActionFunction instead of Play2 filter.
Would you consider using it?
