### ISSUE TITLE
"val res" in READ_ME is not understandable 

### ISSUE THREAD

**Issue by JohnReedLOL** [t2v/play2-auth#165]
val res = Messages.list(FakeRequest().withLoggedIn(config)(1))
       ^ What does "res" stand for? "resistant"? "restraint"? "recessitation"? 

Please change it to something more understandable.

**Comment by scotv** [comment]
`result`, I think

many times, when the code is only one line, or we need a temporary variable to hold the result value, we name the temporary variable as `result`

**Comment by gakuzzzz** [comment]
Yes, it means `result`
