### ISSUE TITLE
Session works on localhost but not on server

### ISSUE THREAD

**Issue by somiclds** [t2v/play2-auth#177]
Authentication and authorization works just fine on localhost, but when I upload my application to production server - it fails.

_LoginSucceeded_ gets called but when user is redirected to required page, authentication fails and user is redirected back to login (_authenticationFailed_ triggers). Cookies and session storage stays empty.

How to solve that?

P.S. I am storing my application in virtual dedicated server. Maybe problem could be in caching?

Thanks.

**Comment by nimmortal** [comment]
Hi!
Maybe you have this line in config trait and delploy on server via 

> activator dist

`cookieSecureOption = play.api.Play.isProd(play.api.Play.current)`

If you are not using SSL then just set it to fasle

**Comment by somiclds** [comment]
I didn't even had this line in my config. Now I have set _cookieSecureOption_ to false as you said and everything works fine! Could you please explain me why it worked locally but not in server?

Thank you!
