### ISSUE TITLE
Using StackAction with BodyParser

### ISSUE THREAD

**Issue by sAnti09** [t2v/play2-auth#68]
The web application I am currently working requires image upload which can only be done with the multipartFormData body parser. My problem now is how to integrate both of them. I tried the simplest possible way by doing StackAction(parser.multipartFormData) which solved the problem with the error I got in my IDE. But when I tried it on the app it doesn't seem to work. It redirects me to the page where unauthenticated users are redirected to even though I am currently logged in. How could I solve the problem? Thank you for your wonderful plugin.

**Comment by fosskers** [comment]
For anyone coming here from the future, I can confirm that this is still the solution.
